### ISSUE TITLE
我在这里似乎是发现了一个错误，我刚学习js不久，不知道我的想法对不对？

### ISSUE THREAD

**Issue by MyPrivateAccount** [wclimb/Koa2-blog#1]
`else {
        connection.query(sql, values, ( err, rows) => {

          if ( err ) {
            reject( err )
          } else {
            resolve( rows )
          }
          connection.release()
        })`这是你的mysql.js中的一段代码其中connection.release()看起来永远也不会执行

**Comment by wunci** [comment]
@MyPrivateAccount 你好，这段代码是可以被执行的，你可以试试这段代码示例
```
let promise = new Promise(function(resolve, reject) {
  console.log('Promise');
  resolve();
  console.log('我被执行了')
});
promise.then(function() {
  console.log('Resolved.');
});
console.log('Hi!');
```
欢迎一起交流学习
