### ISSUE TITLE
非常不错的教程。

### ISSUE THREAD

**Issue by sorkindeng** [wclimb/Koa2-blog#10]
非常不错的教程，学习了，已star。

按照教程文档一步一步下来，文档中有几个小错误，但是参考了源码后都很容易解决：
1.在“实现注册页面”那里，有一个拼写错误，singup.js，实际上应该是signup.js 。
2.在“发表文章”那里，代码 router.get('/posts/:postId'...，代码贴少了，没有处理评论的相关内容。
3.删除评论时，删除某一条时，会将这一条以及之后的所有评论删除。源码中没有这个问题。
4.安装supervisor时，要么通过-g来安装，要么就通过在package.json中加script来做。

**Comment by wunci** [comment]
感谢你的阅读，教程是比较早之前写的，你可以参照现在的来写，现在的比之前的完善点，有什么问题还望尽快反馈哈
