### ISSUE TITLE
@*

### ISSUE THREAD

**Issue by lp110lp** [wclimb/Koa2-blog#12]
let query = function( sql, values ) {

  return new Promise(( resolve, reject ) => {
    pool.getConnection(function(err, connection) {
      if (err) {
        resolve( err )--------->这里为什么不是reject啊
      } else {
        connection.query(sql, values, ( err, rows) => {

          if ( err ) {
            reject( err )
          } else {
            resolve( rows )
          }
          connection.release()
        })
      }
    })
  })

}

**Comment by wunci** [comment]
@lp110lp 没发现这个问题，应该写reject的。稍后更正一下
