### ISSUE TITLE
在登录成功后进入 posts 页面重定向次数过多

### ISSUE THREAD

**Issue by Chris-wei** [wclimb/Koa2-blog#2]
router.get('/', async(ctx, next) => {
	ctx.redirect('/posts')
})
导致重定向次数过多，删掉正常

**Comment by wunci** [comment]
@Chris-wei 登录成功后会自动跳转到`/posts`页面，不应该会出现重定向错误呀，而且这段代码只是会在刚进来页面的时候进行重定向
