### ISSUE TITLE
大神你用的mysql客户端是什么版本 

### ISSUE THREAD

**Issue by weibingbing5101** [wclimb/Koa2-blog#22]
server is running at http://localhost:3000
(node:14693) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
(node:14693) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

像是sql的客户端不支持

**Comment by wunci** [comment]
http://www.jb51.net/article/139923.htm    
看看这个，之前也有人问过我，安装的问题，我的版本是5.7
