### ISSUE TITLE
md5加密的问题

### ISSUE THREAD

**Issue by 447166939** [wclimb/Koa2-blog#25]
你好，我是个初学者，我看了你的代码有些不是很懂，为什么密码是在服务器登录验证时加密，而不是在前端加密，前端发送的是明文密码，这样子在后端加密有什么作用？

**Comment by wunci** [comment]
首先明文传输是没问题的，如果是http的话确实不安全，上https差不多，其次一般都是后端来加密的，前端加密没有安全性可言，你要想前端代码都是公开的，一般后台自己写的加密算法，还有就是一般不会用md5加密

**Comment by 447166939** [comment]
我主要是不明白这加密的作用，是让别人拿到你的数据库也不知道密码是多少吗？

**Comment by wunci** [comment]
@447166939 数据库可能会泄露，前段时间A站、摩拜就是

**Comment by 447166939** [comment]
哦，谢谢。

**Comment by 447166939** [comment]
今天又去看了些加密的相关的东西，如果后端用非对称算法加密密钥传给前端，前端解密密钥，然后用得到的密钥用对称算法加密，这样前端代码虽然是公开的，别人没有密钥也是解不了密的吧。可是如果只在后端的数据库里加密的话，如果数据库都泄露了了的话，根本就没有安全可言了，加不加密不是没多大差别吗，而且如果是在前端加密的话，存在数据库里的密码也是密文啊，别人也不知道密码啊
