### ISSUE TITLE
接口重复调用

### ISSUE THREAD

**Issue by muzishuiji** [wclimb/Koa2-blog#3]
我不知道为什么，我和你一摸一样的方法，比如发表文章这个接口，我点击发表按钮，接口那里打印
 var postData = ctx.request.body
    console.log('/create', postData)
像这样的打印，会打印两遍，会导致我的页面没法跳转到所有文章的列表页，我很苦恼，不知道什么原因，之前登录还是注册好像也是这样，求救！！！！！

**Comment by muzishuiji** [comment]
我找到原因了，原因就是发表的按钮我用的button，我没有写type=button
好神奇，这是为什么呢？不解，我把button换成div就可以正常跳转，使用button把他的属性type=button加上也可以正常跳转。好神奇。

**Comment by wunci** [comment]
@muzishuiji 因为你用button会提交form表单（这是第一次），然后又通过ajax提交了（这是第二次），所以才会出现你出现的问题，页面第一次提交就跳转了，并不是通过ajax成功后跳转的，所以跳转不到指定的页面哟！

**Comment by muzishuiji** [comment]
嗯嗯嗯，好的呢。我后面也发现了这个道理。可能我不设置type为btton它就会默认我的button的type为submit然后就导致接口重复调用了，谢谢你啦！顺便说一句。很感谢你这个教程的分享。写的很细致明了，很适合初学者。谢谢你带我入了门😙

**Comment by wunci** [comment]
感谢支持哈
