### ISSUE TITLE
关于部署问题

### ISSUE THREAD

**Issue by OweQian** [wclimb/Koa2-blog#32]
请大佬帮忙看看如何解决这个问题？感谢
pm2 start index.js
pm2 log
<img width="1696" alt="wechatb05503a777188109169493583bde3629" src="https://user-images.githubusercontent.com/25632596/48981741-86eb2f00-f114-11e8-95b3-22f32b17ff34.png">

**Comment by wunci** [comment]
@wangqian2017 数据库连接的问题
