### ISSUE TITLE
mysql.js 多个数据库语句操作报错

### ISSUE THREAD

**Issue by changfu2015** [wclimb/Koa2-blog#8]
`delete from posts where id = ${id};
  delete from article where postsId = ${id};`
数据库执行没问题

let deleteArticle = function(id){
  console.log(id)
  let _sql =`delete from posts where id = ${id};
  delete from article where postsId = ${id};`
  return query(_sql)
}
ER_PARSE_ERROR: You have an error in your SQL syntax; check
 the manual that corresponds to your MySQL server version for the right syntax t
o use near 'delete from posts where folderId = 41' at line 2

**Comment by wclimb** [comment]
@changfu2015 老哥多表删除不是这样的，可以这样试试
`DELETE a,b FROM table1 a,table2 b WHERE a.id = b.uid AND a.id = '1'`

**Comment by wunci** [comment]
@changfu2015 老哥多表删除不是这样的，可以这样试试(我没试过哈)
`DELETE a,b FROM article postsId,posts id WHERE a.postsId = b.id`
